version: "3.7"
services:
  api:
    working_dir: /usr/src/app
    image: node:18-alpine
    volumes:
      - .:/usr/src/app
    command: ["npm" , "start"]
    env_file:
     - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    external_links:
      - db
  db:
    image: mongo:6
    restart: always
    volumes:
      - db-data:/data/db
    ports:
     - '27012:27017'
  mongo-express: 
    container_name: mongo-express
    image: mongo-express
    ports: 
     - '8083:8081'
    environment:
     - ME_CONFIG_MONGODB_URL=mongodb://db:27017
    links:
      - db

volumes:
  db-data:


